/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainTransactionsRouteImport } from './routes/_main/transactions'
import { Route as MainMyCardsRouteImport } from './routes/_main/my-cards'
import { Route as MainMarketingRouteImport } from './routes/_main/marketing'
import { Route as MainHrRouteImport } from './routes/_main/hr'
import { Route as AuthLoginRouteRouteImport } from './routes/auth/login/route'
import { Route as AuthForgotPasswordRouteRouteImport } from './routes/auth/forgot-password/route'
import { Route as AuthResetPasswordTokenRouteRouteImport } from './routes/auth/reset-password/$token/route'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainTransactionsRoute = MainTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => MainRoute,
} as any)
const MainMyCardsRoute = MainMyCardsRouteImport.update({
  id: '/my-cards',
  path: '/my-cards',
  getParentRoute: () => MainRoute,
} as any)
const MainMarketingRoute = MainMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => MainRoute,
} as any)
const MainHrRoute = MainHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => MainRoute,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRouteRoute = AuthForgotPasswordRouteRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordTokenRouteRoute =
  AuthResetPasswordTokenRouteRouteImport.update({
    id: '/reset-password/$token',
    path: '/reset-password/$token',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRoute
  '/': typeof MainIndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/hr': typeof MainHrRoute
  '/marketing': typeof MainMarketingRoute
  '/my-cards': typeof MainMyCardsRoute
  '/transactions': typeof MainTransactionsRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRouteRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/hr': typeof MainHrRoute
  '/marketing': typeof MainMarketingRoute
  '/my-cards': typeof MainMyCardsRoute
  '/transactions': typeof MainTransactionsRoute
  '/': typeof MainIndexRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRoute
  '/_main': typeof MainRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/_main/hr': typeof MainHrRoute
  '/_main/marketing': typeof MainMarketingRoute
  '/_main/my-cards': typeof MainMyCardsRoute
  '/_main/transactions': typeof MainTransactionsRoute
  '/_main/': typeof MainIndexRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/onboarding'
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/hr'
    | '/marketing'
    | '/my-cards'
    | '/transactions'
    | '/auth/reset-password/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/onboarding'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/hr'
    | '/marketing'
    | '/my-cards'
    | '/transactions'
    | '/'
    | '/auth/reset-password/$token'
  id:
    | '__root__'
    | '/auth'
    | '/onboarding'
    | '/_main'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/_main/hr'
    | '/_main/marketing'
    | '/_main/my-cards'
    | '/_main/transactions'
    | '/_main/'
    | '/auth/reset-password/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRoute
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/transactions': {
      id: '/_main/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof MainTransactionsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/my-cards': {
      id: '/_main/my-cards'
      path: '/my-cards'
      fullPath: '/my-cards'
      preLoaderRoute: typeof MainMyCardsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/marketing': {
      id: '/_main/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MainMarketingRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/hr': {
      id: '/_main/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof MainHrRouteImport
      parentRoute: typeof MainRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password/$token': {
      id: '/auth/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/auth/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRouteRoute: typeof AuthForgotPasswordRouteRoute
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
  AuthResetPasswordTokenRouteRoute: typeof AuthResetPasswordTokenRouteRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRouteRoute: AuthForgotPasswordRouteRoute,
  AuthLoginRouteRoute: AuthLoginRouteRoute,
  AuthResetPasswordTokenRouteRoute: AuthResetPasswordTokenRouteRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainRouteChildren {
  MainHrRoute: typeof MainHrRoute
  MainMarketingRoute: typeof MainMarketingRoute
  MainMyCardsRoute: typeof MainMyCardsRoute
  MainTransactionsRoute: typeof MainTransactionsRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainHrRoute: MainHrRoute,
  MainMarketingRoute: MainMarketingRoute,
  MainMyCardsRoute: MainMyCardsRoute,
  MainTransactionsRoute: MainTransactionsRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRoute,
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
