/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainTransactionsRouteImport } from './routes/_main/transactions'
import { Route as MainMyCardsRouteImport } from './routes/_main/my-cards'
import { Route as MainMarketingRouteImport } from './routes/_main/marketing'
import { Route as MainHrRouteImport } from './routes/_main/hr'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainTransactionsRoute = MainTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => MainRoute,
} as any)
const MainMyCardsRoute = MainMyCardsRouteImport.update({
  id: '/my-cards',
  path: '/my-cards',
  getParentRoute: () => MainRoute,
} as any)
const MainMarketingRoute = MainMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => MainRoute,
} as any)
const MainHrRoute = MainHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/hr': typeof MainHrRoute
  '/marketing': typeof MainMarketingRoute
  '/my-cards': typeof MainMyCardsRoute
  '/transactions': typeof MainTransactionsRoute
}
export interface FileRoutesByTo {
  '/hr': typeof MainHrRoute
  '/marketing': typeof MainMarketingRoute
  '/my-cards': typeof MainMyCardsRoute
  '/transactions': typeof MainTransactionsRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/hr': typeof MainHrRoute
  '/_main/marketing': typeof MainMarketingRoute
  '/_main/my-cards': typeof MainMyCardsRoute
  '/_main/transactions': typeof MainTransactionsRoute
  '/_main/': typeof MainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hr' | '/marketing' | '/my-cards' | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/hr' | '/marketing' | '/my-cards' | '/transactions' | '/'
  id:
    | '__root__'
    | '/_main'
    | '/_main/hr'
    | '/_main/marketing'
    | '/_main/my-cards'
    | '/_main/transactions'
    | '/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/transactions': {
      id: '/_main/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof MainTransactionsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/my-cards': {
      id: '/_main/my-cards'
      path: '/my-cards'
      fullPath: '/my-cards'
      preLoaderRoute: typeof MainMyCardsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/marketing': {
      id: '/_main/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MainMarketingRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/hr': {
      id: '/_main/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof MainHrRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainHrRoute: typeof MainHrRoute
  MainMarketingRoute: typeof MainMarketingRoute
  MainMyCardsRoute: typeof MainMyCardsRoute
  MainTransactionsRoute: typeof MainTransactionsRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainHrRoute: MainHrRoute,
  MainMarketingRoute: MainMarketingRoute,
  MainMyCardsRoute: MainMyCardsRoute,
  MainTransactionsRoute: MainTransactionsRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
