/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainWorkflowsRouteImport } from './routes/_main/workflows'
import { Route as MainWalletsRouteImport } from './routes/_main/wallets'
import { Route as MainVendorsInvoicesRouteImport } from './routes/_main/vendors-invoices'
import { Route as MainUsersRouteImport } from './routes/_main/users'
import { Route as MainTransactionsRouteImport } from './routes/_main/transactions'
import { Route as MainReportsRouteImport } from './routes/_main/reports'
import { Route as MainPoliciesRouteImport } from './routes/_main/policies'
import { Route as MainMyCardsRouteImport } from './routes/_main/my-cards'
import { Route as MainMarketingRouteImport } from './routes/_main/marketing'
import { Route as MainHrRouteImport } from './routes/_main/hr'
import { Route as MainDepartmentsRouteImport } from './routes/_main/departments'
import { Route as MainAuditLogRouteImport } from './routes/_main/audit-log'
import { Route as MainApprovalsRouteImport } from './routes/_main/approvals'
import { Route as AuthLoginRouteRouteImport } from './routes/auth/login/route'
import { Route as AuthForgotPasswordRouteRouteImport } from './routes/auth/forgot-password/route'
import { Route as MainBudgetsRouteRouteImport } from './routes/_main/budgets/route'
import { Route as MainSpendRequestsIndexRouteImport } from './routes/_main/spend-requests/index'
import { Route as AuthResetPasswordTokenRouteRouteImport } from './routes/auth/reset-password/$token/route'
import { Route as MainSpendRequestsIdRouteRouteImport } from './routes/_main/spend-requests/$id/route'
import { Route as MainAdminWorkflowsRouteRouteImport } from './routes/_main/admin/workflows/route'
import { Route as MainAdminPoliciesRouteRouteImport } from './routes/_main/admin/policies/route'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainWorkflowsRoute = MainWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => MainRoute,
} as any)
const MainWalletsRoute = MainWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => MainRoute,
} as any)
const MainVendorsInvoicesRoute = MainVendorsInvoicesRouteImport.update({
  id: '/vendors-invoices',
  path: '/vendors-invoices',
  getParentRoute: () => MainRoute,
} as any)
const MainUsersRoute = MainUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => MainRoute,
} as any)
const MainTransactionsRoute = MainTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => MainRoute,
} as any)
const MainReportsRoute = MainReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => MainRoute,
} as any)
const MainPoliciesRoute = MainPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => MainRoute,
} as any)
const MainMyCardsRoute = MainMyCardsRouteImport.update({
  id: '/my-cards',
  path: '/my-cards',
  getParentRoute: () => MainRoute,
} as any)
const MainMarketingRoute = MainMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => MainRoute,
} as any)
const MainHrRoute = MainHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => MainRoute,
} as any)
const MainDepartmentsRoute = MainDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => MainRoute,
} as any)
const MainAuditLogRoute = MainAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => MainRoute,
} as any)
const MainApprovalsRoute = MainApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => MainRoute,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRouteRoute = AuthForgotPasswordRouteRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MainBudgetsRouteRoute = MainBudgetsRouteRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => MainRoute,
} as any)
const MainSpendRequestsIndexRoute = MainSpendRequestsIndexRouteImport.update({
  id: '/spend-requests/',
  path: '/spend-requests/',
  getParentRoute: () => MainRoute,
} as any)
const AuthResetPasswordTokenRouteRoute =
  AuthResetPasswordTokenRouteRouteImport.update({
    id: '/reset-password/$token',
    path: '/reset-password/$token',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const MainSpendRequestsIdRouteRoute =
  MainSpendRequestsIdRouteRouteImport.update({
    id: '/spend-requests/$id',
    path: '/spend-requests/$id',
    getParentRoute: () => MainRoute,
  } as any)
const MainAdminWorkflowsRouteRoute = MainAdminWorkflowsRouteRouteImport.update({
  id: '/admin/workflows',
  path: '/admin/workflows',
  getParentRoute: () => MainRoute,
} as any)
const MainAdminPoliciesRouteRoute = MainAdminPoliciesRouteRouteImport.update({
  id: '/admin/policies',
  path: '/admin/policies',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRoute
  '/': typeof MainIndexRoute
  '/budgets': typeof MainBudgetsRouteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/approvals': typeof MainApprovalsRoute
  '/audit-log': typeof MainAuditLogRoute
  '/departments': typeof MainDepartmentsRoute
  '/hr': typeof MainHrRoute
  '/marketing': typeof MainMarketingRoute
  '/my-cards': typeof MainMyCardsRoute
  '/policies': typeof MainPoliciesRoute
  '/reports': typeof MainReportsRoute
  '/transactions': typeof MainTransactionsRoute
  '/users': typeof MainUsersRoute
  '/vendors-invoices': typeof MainVendorsInvoicesRoute
  '/wallets': typeof MainWalletsRoute
  '/workflows': typeof MainWorkflowsRoute
  '/admin/policies': typeof MainAdminPoliciesRouteRoute
  '/admin/workflows': typeof MainAdminWorkflowsRouteRoute
  '/spend-requests/$id': typeof MainSpendRequestsIdRouteRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRouteRoute
  '/spend-requests/': typeof MainSpendRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRoute
  '/budgets': typeof MainBudgetsRouteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/approvals': typeof MainApprovalsRoute
  '/audit-log': typeof MainAuditLogRoute
  '/departments': typeof MainDepartmentsRoute
  '/hr': typeof MainHrRoute
  '/marketing': typeof MainMarketingRoute
  '/my-cards': typeof MainMyCardsRoute
  '/policies': typeof MainPoliciesRoute
  '/reports': typeof MainReportsRoute
  '/transactions': typeof MainTransactionsRoute
  '/users': typeof MainUsersRoute
  '/vendors-invoices': typeof MainVendorsInvoicesRoute
  '/wallets': typeof MainWalletsRoute
  '/workflows': typeof MainWorkflowsRoute
  '/': typeof MainIndexRoute
  '/admin/policies': typeof MainAdminPoliciesRouteRoute
  '/admin/workflows': typeof MainAdminWorkflowsRouteRoute
  '/spend-requests/$id': typeof MainSpendRequestsIdRouteRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRouteRoute
  '/spend-requests': typeof MainSpendRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRoute
  '/_main': typeof MainRouteWithChildren
  '/_main/budgets': typeof MainBudgetsRouteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/_main/approvals': typeof MainApprovalsRoute
  '/_main/audit-log': typeof MainAuditLogRoute
  '/_main/departments': typeof MainDepartmentsRoute
  '/_main/hr': typeof MainHrRoute
  '/_main/marketing': typeof MainMarketingRoute
  '/_main/my-cards': typeof MainMyCardsRoute
  '/_main/policies': typeof MainPoliciesRoute
  '/_main/reports': typeof MainReportsRoute
  '/_main/transactions': typeof MainTransactionsRoute
  '/_main/users': typeof MainUsersRoute
  '/_main/vendors-invoices': typeof MainVendorsInvoicesRoute
  '/_main/wallets': typeof MainWalletsRoute
  '/_main/workflows': typeof MainWorkflowsRoute
  '/_main/': typeof MainIndexRoute
  '/_main/admin/policies': typeof MainAdminPoliciesRouteRoute
  '/_main/admin/workflows': typeof MainAdminWorkflowsRouteRoute
  '/_main/spend-requests/$id': typeof MainSpendRequestsIdRouteRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRouteRoute
  '/_main/spend-requests/': typeof MainSpendRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/onboarding'
    | '/'
    | '/budgets'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/approvals'
    | '/audit-log'
    | '/departments'
    | '/hr'
    | '/marketing'
    | '/my-cards'
    | '/policies'
    | '/reports'
    | '/transactions'
    | '/users'
    | '/vendors-invoices'
    | '/wallets'
    | '/workflows'
    | '/admin/policies'
    | '/admin/workflows'
    | '/spend-requests/$id'
    | '/auth/reset-password/$token'
    | '/spend-requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/onboarding'
    | '/budgets'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/approvals'
    | '/audit-log'
    | '/departments'
    | '/hr'
    | '/marketing'
    | '/my-cards'
    | '/policies'
    | '/reports'
    | '/transactions'
    | '/users'
    | '/vendors-invoices'
    | '/wallets'
    | '/workflows'
    | '/'
    | '/admin/policies'
    | '/admin/workflows'
    | '/spend-requests/$id'
    | '/auth/reset-password/$token'
    | '/spend-requests'
  id:
    | '__root__'
    | '/auth'
    | '/onboarding'
    | '/_main'
    | '/_main/budgets'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/_main/approvals'
    | '/_main/audit-log'
    | '/_main/departments'
    | '/_main/hr'
    | '/_main/marketing'
    | '/_main/my-cards'
    | '/_main/policies'
    | '/_main/reports'
    | '/_main/transactions'
    | '/_main/users'
    | '/_main/vendors-invoices'
    | '/_main/wallets'
    | '/_main/workflows'
    | '/_main/'
    | '/_main/admin/policies'
    | '/_main/admin/workflows'
    | '/_main/spend-requests/$id'
    | '/auth/reset-password/$token'
    | '/_main/spend-requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRoute
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/workflows': {
      id: '/_main/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof MainWorkflowsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/wallets': {
      id: '/_main/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof MainWalletsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/vendors-invoices': {
      id: '/_main/vendors-invoices'
      path: '/vendors-invoices'
      fullPath: '/vendors-invoices'
      preLoaderRoute: typeof MainVendorsInvoicesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/users': {
      id: '/_main/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof MainUsersRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/transactions': {
      id: '/_main/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof MainTransactionsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/reports': {
      id: '/_main/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof MainReportsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/policies': {
      id: '/_main/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof MainPoliciesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/my-cards': {
      id: '/_main/my-cards'
      path: '/my-cards'
      fullPath: '/my-cards'
      preLoaderRoute: typeof MainMyCardsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/marketing': {
      id: '/_main/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MainMarketingRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/hr': {
      id: '/_main/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof MainHrRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/departments': {
      id: '/_main/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof MainDepartmentsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/audit-log': {
      id: '/_main/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof MainAuditLogRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/approvals': {
      id: '/_main/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof MainApprovalsRouteImport
      parentRoute: typeof MainRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_main/budgets': {
      id: '/_main/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof MainBudgetsRouteRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/spend-requests/': {
      id: '/_main/spend-requests/'
      path: '/spend-requests'
      fullPath: '/spend-requests/'
      preLoaderRoute: typeof MainSpendRequestsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/auth/reset-password/$token': {
      id: '/auth/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/auth/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_main/spend-requests/$id': {
      id: '/_main/spend-requests/$id'
      path: '/spend-requests/$id'
      fullPath: '/spend-requests/$id'
      preLoaderRoute: typeof MainSpendRequestsIdRouteRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/admin/workflows': {
      id: '/_main/admin/workflows'
      path: '/admin/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof MainAdminWorkflowsRouteRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/admin/policies': {
      id: '/_main/admin/policies'
      path: '/admin/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof MainAdminPoliciesRouteRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRouteRoute: typeof AuthForgotPasswordRouteRoute
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
  AuthResetPasswordTokenRouteRoute: typeof AuthResetPasswordTokenRouteRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRouteRoute: AuthForgotPasswordRouteRoute,
  AuthLoginRouteRoute: AuthLoginRouteRoute,
  AuthResetPasswordTokenRouteRoute: AuthResetPasswordTokenRouteRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainRouteChildren {
  MainBudgetsRouteRoute: typeof MainBudgetsRouteRoute
  MainApprovalsRoute: typeof MainApprovalsRoute
  MainAuditLogRoute: typeof MainAuditLogRoute
  MainDepartmentsRoute: typeof MainDepartmentsRoute
  MainHrRoute: typeof MainHrRoute
  MainMarketingRoute: typeof MainMarketingRoute
  MainMyCardsRoute: typeof MainMyCardsRoute
  MainPoliciesRoute: typeof MainPoliciesRoute
  MainReportsRoute: typeof MainReportsRoute
  MainTransactionsRoute: typeof MainTransactionsRoute
  MainUsersRoute: typeof MainUsersRoute
  MainVendorsInvoicesRoute: typeof MainVendorsInvoicesRoute
  MainWalletsRoute: typeof MainWalletsRoute
  MainWorkflowsRoute: typeof MainWorkflowsRoute
  MainIndexRoute: typeof MainIndexRoute
  MainAdminPoliciesRouteRoute: typeof MainAdminPoliciesRouteRoute
  MainAdminWorkflowsRouteRoute: typeof MainAdminWorkflowsRouteRoute
  MainSpendRequestsIdRouteRoute: typeof MainSpendRequestsIdRouteRoute
  MainSpendRequestsIndexRoute: typeof MainSpendRequestsIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainBudgetsRouteRoute: MainBudgetsRouteRoute,
  MainApprovalsRoute: MainApprovalsRoute,
  MainAuditLogRoute: MainAuditLogRoute,
  MainDepartmentsRoute: MainDepartmentsRoute,
  MainHrRoute: MainHrRoute,
  MainMarketingRoute: MainMarketingRoute,
  MainMyCardsRoute: MainMyCardsRoute,
  MainPoliciesRoute: MainPoliciesRoute,
  MainReportsRoute: MainReportsRoute,
  MainTransactionsRoute: MainTransactionsRoute,
  MainUsersRoute: MainUsersRoute,
  MainVendorsInvoicesRoute: MainVendorsInvoicesRoute,
  MainWalletsRoute: MainWalletsRoute,
  MainWorkflowsRoute: MainWorkflowsRoute,
  MainIndexRoute: MainIndexRoute,
  MainAdminPoliciesRouteRoute: MainAdminPoliciesRouteRoute,
  MainAdminWorkflowsRouteRoute: MainAdminWorkflowsRouteRoute,
  MainSpendRequestsIdRouteRoute: MainSpendRequestsIdRouteRoute,
  MainSpendRequestsIndexRoute: MainSpendRequestsIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRoute,
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
